### PR TITLE
overrides v4.1.2 (redux)

### PR DESCRIPTION
**Pull request by h-vetinari**
This feedstock has been languishing a while. Upstream is already at 6.x, but it's my intention to revive the feedstock and have at least one build for each major version.

Closes #16
Closes #15
Closes #14
Closes #13

### CODE REVIEW

**Comment by h-vetinari** [comment]
@conda-forge/core 
This feedstock has been languishing for almost 1.5 years - upstream has moved on two major versions in the meantime (6.x), but the bot stopped raising PRs. I've added myself to maintainers, and would make sure we have at least one build per major version.

Would appreciate if someone can merge this. 🙃

**Comment by beckermr** [comment]
I added you to the feedstock in another PR. You should have permissions to fix the conflicts here and merge!

**Comment by h-vetinari** [comment]
> I added you to the feedstock in another PR. You should have permissions to fix the conflicts here and merge!

Thanks! :)

**Comment by h-vetinari** [comment]
Seems the bot forgets to add a newline at the end when adding new maintainers... 🙃

**Pull request merged**
